{
    'name': 'Odoo Shopify Connector Automation',
    'version': '17.0.1.0.0',
    'summary': 'Advanced Shopify-Odoo Connector by ECOSIRE (PRIVATE) LIMITED',
    'description': 'Comprehensive, real-time, and automated integration between Odoo and Shopify. Developed by ECOSIRE (PRIVATE) LIMITED.',
    'author': 'ECOSIRE (PRIVATE) LIMITED',
    'website': 'https://www.ecosire.com/',
    'category': 'Connector',
    'depends': ['base', 'sale_management', 'stock', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'views/menu.xml',
        'views/shopify_instance_view.xml',
        'views/shopify_product_view.xml',
        'views/shopify_order_view.xml',
        'views/shopify_customer_view.xml',
        'views/shopify_queue_job_view.xml',
        'views/shopify_log_view.xml',
        'views/dashboard_view.xml',
        'views/shopify_cron_view.xml',
        'wizard/manual_sync_wizard_view.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
} 